export const countries = [
  { id: "US", label: "United States" },
  { id: "CA", label: "Canada" },
  { id: "AR", label: "Argentina" },
  { id: "AU", label: "Australia" },
  { id: "BE", label: "Belgium" },
  { id: "BR", label: "Brazil" },
  { id: "KH", label: "Cambodia" },
  { id: "CN", label: "China" },
  { id: "CO", label: "Colombia" },
  { id: "HR", label: "Croatia" },
  { id: "CU", label: "Cuba" },
  { id: "EG", label: "Egypt" },
  { id: "FR", label: "France" },
  { id: "DE", label: "Germany" },
  { id: "GL", label: "Greenland" },
  { id: "HK", label: "Hong Kong" },
  { id: "IN", label: "India" },
  { id: "IE", label: "Ireland" },
  { id: "IT", label: "Italy" },
  { id: "JP", label: "Japan" },
  { id: "MY", label: "Malaysia" },
  { id: "VN", label: "Viet Nam" },
  { id: "EU", label: "Europe" },
];
